spring:
  datasource:
    url: ${POSTGRES_DB_URL:jdbc:postgresql://localhost:5432/notifications?reWriteBatchedInserts=true}
    username: ${POSTGRES_DB_USER:notifications_db_user}
    password: ${POSTGRES_DB_PASS:notifications_db_pass}

  jpa:
    properties:
      hibernate:
        generate_statistics: false

  kafka:
    producer:
      properties:
        auto.register.schemas: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.apache.kafka: INFO
    org.hibernate.SQL: INFO
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: INFO